"""add name  to client info

Revision ID: 1e08e6ce65f1
Revises: d11357299ccc
Create Date: 2025-11-24 00:25:45.980599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e08e6ce65f1'
down_revision: Union[str, Sequence[str], None] = 'd11357299ccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_info', sa.Column('name', sa.String(length=255), nullable=True))
    op.alter_column('client_info', 'method_type',
               existing_type=postgresql.ENUM('Email', 'WhatsApp', 'Verbal', 'In Person', 'Other', name='methodenum'),
               type_=sa.Enum('email', 'whats_app', 'verbal', 'in_person', 'other', name='methodenum', native_enum=False),
               existing_nullable=False)
    op.alter_column('client_info', 'booking_request_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client_info', 'booking_request_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('client_info', 'method_type',
               existing_type=sa.Enum('email', 'whats_app', 'verbal', 'in_person', 'other', name='methodenum', native_enum=False),
               type_=postgresql.ENUM('Email', 'WhatsApp', 'Verbal', 'In Person', 'Other', name='methodenum'),
               existing_nullable=False)
    op.drop_column('client_info', 'name')
    # ### end Alembic commands ###
