"""add new columns

Revision ID: 6425ab9f00b5
Revises: f8f917784957
Create Date: 2025-11-15 05:37:05.154834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6425ab9f00b5'
down_revision: Union[str, Sequence[str], None] = 'f8f917784957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargo_descriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cargo_descriptions_id'), 'cargo_descriptions', ['id'], unique=False)
    op.create_table('carrier_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carrier_info_id'), 'carrier_info', ['id'], unique=False)
    op.create_table('vessel_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vessel_info_id'), 'vessel_info', ['id'], unique=False)
    op.add_column('booking_confirmations', sa.Column('carrier_id', sa.Integer(), nullable=False))
    op.add_column('booking_confirmations', sa.Column('shipper_id', sa.Integer(), nullable=False))
    op.add_column('booking_confirmations', sa.Column('port_of_load_id', sa.Integer(), nullable=False))
    op.add_column('booking_confirmations', sa.Column('port_of_discharge_id', sa.Integer(), nullable=False))
    op.add_column('booking_confirmations', sa.Column('vessel_id', sa.Integer(), nullable=False))
    op.add_column('booking_confirmations', sa.Column('container_size_id', sa.Integer(), nullable=True))
    op.add_column('booking_confirmations', sa.Column('hs_code_id', sa.Integer(), nullable=True))
    op.add_column('booking_confirmations', sa.Column('cargo_description_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'booking_confirmations', 'ports', ['port_of_discharge_id'], ['id'])
    op.create_foreign_key(None, 'booking_confirmations', 'users', ['shipper_id'], ['id'])
    op.create_foreign_key(None, 'booking_confirmations', 'carrier_info', ['carrier_id'], ['id'])
    op.create_foreign_key(None, 'booking_confirmations', 'hs_codes', ['hs_code_id'], ['id'])
    op.create_foreign_key(None, 'booking_confirmations', 'vessel_info', ['vessel_id'], ['id'])
    op.create_foreign_key(None, 'booking_confirmations', 'cargo_descriptions', ['cargo_description_id'], ['id'])
    op.create_foreign_key(None, 'booking_confirmations', 'container_sizes', ['container_size_id'], ['id'])
    op.create_foreign_key(None, 'booking_confirmations', 'ports', ['port_of_load_id'], ['id'])
    op.drop_column('booking_confirmations', 'container_size')
    op.drop_column('booking_confirmations', 'port_of_load')
    op.drop_column('booking_confirmations', 'hs_code')
    op.drop_column('booking_confirmations', 'carrier_name')
    op.drop_column('booking_confirmations', 'port_of_discharge')
    op.drop_column('booking_confirmations', 'vessel_name')
    op.drop_column('booking_confirmations', 'cargo_description')
    op.drop_column('booking_confirmations', 'shipper')
    op.add_column('client_info', sa.Column('shipper_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'client_info', 'users', ['shipper_id'], ['id'])
    op.add_column('users', sa.Column('address', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'address')
    op.drop_constraint(None, 'client_info', type_='foreignkey')
    op.drop_column('client_info', 'shipper_id')
    op.add_column('booking_confirmations', sa.Column('shipper', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('booking_confirmations', sa.Column('cargo_description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('booking_confirmations', sa.Column('vessel_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('booking_confirmations', sa.Column('port_of_discharge', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('booking_confirmations', sa.Column('carrier_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('booking_confirmations', sa.Column('hs_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('booking_confirmations', sa.Column('port_of_load', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('booking_confirmations', sa.Column('container_size', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'booking_confirmations', type_='foreignkey')
    op.drop_constraint(None, 'booking_confirmations', type_='foreignkey')
    op.drop_constraint(None, 'booking_confirmations', type_='foreignkey')
    op.drop_constraint(None, 'booking_confirmations', type_='foreignkey')
    op.drop_constraint(None, 'booking_confirmations', type_='foreignkey')
    op.drop_constraint(None, 'booking_confirmations', type_='foreignkey')
    op.drop_constraint(None, 'booking_confirmations', type_='foreignkey')
    op.drop_constraint(None, 'booking_confirmations', type_='foreignkey')
    op.drop_column('booking_confirmations', 'cargo_description_id')
    op.drop_column('booking_confirmations', 'hs_code_id')
    op.drop_column('booking_confirmations', 'container_size_id')
    op.drop_column('booking_confirmations', 'vessel_id')
    op.drop_column('booking_confirmations', 'port_of_discharge_id')
    op.drop_column('booking_confirmations', 'port_of_load_id')
    op.drop_column('booking_confirmations', 'shipper_id')
    op.drop_column('booking_confirmations', 'carrier_id')
    op.drop_index(op.f('ix_vessel_info_id'), table_name='vessel_info')
    op.drop_table('vessel_info')
    op.drop_index(op.f('ix_carrier_info_id'), table_name='carrier_info')
    op.drop_table('carrier_info')
    op.drop_index(op.f('ix_cargo_descriptions_id'), table_name='cargo_descriptions')
    op.drop_table('cargo_descriptions')
    # ### end Alembic commands ###
