"""change column in shippings

Revision ID: 81351e2503c2
Revises: a4941ca1df30
Create Date: 2025-11-29 03:32:18.257509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81351e2503c2'
down_revision: Union[str, Sequence[str], None] = 'a4941ca1df30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipping_instructions', sa.Column('shipper_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'shipping_instructions', 'users', ['shipper_id'], ['id'])
    op.drop_column('shipping_instructions', 'shipper')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipping_instructions', sa.Column('shipper', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'shipping_instructions', type_='foreignkey')
    op.drop_column('shipping_instructions', 'shipper_id')
    # ### end Alembic commands ###
