"""new column

Revision ID: a2a731255f22
Revises: 1e08e6ce65f1
Create Date: 2025-11-24 01:01:02.217162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2a731255f22'
down_revision: Union[str, Sequence[str], None] = '1e08e6ce65f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_request_client_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_request_id', sa.Integer(), nullable=False),
    sa.Column('client_info_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_request_id'], ['booking_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_info_id'], ['client_info.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_request_client_info_id'), 'booking_request_client_info', ['id'], unique=False)
    op.drop_constraint(op.f('client_info_booking_request_id_fkey'), 'client_info', type_='foreignkey')
    op.drop_column('client_info', 'booking_request_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_info', sa.Column('booking_request_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('client_info_booking_request_id_fkey'), 'client_info', 'booking_requests', ['booking_request_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_booking_request_client_info_id'), table_name='booking_request_client_info')
    op.drop_table('booking_request_client_info')
    # ### end Alembic commands ###
