"""add new columns

Revision ID: a620696c86cc
Revises: 6425ab9f00b5
Create Date: 2025-11-15 17:22:46.572092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a620696c86cc'
down_revision: Union[str, Sequence[str], None] = '6425ab9f00b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_info', sa.Column('company_registration_no', sa.String(length=255), nullable=True))
    op.add_column('client_info', sa.Column('tax_id', sa.String(length=255), nullable=True))
    op.add_column('client_info', sa.Column('company_vat_no', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('client_info_shipper_id_fkey'), 'client_info', type_='foreignkey')
    op.drop_column('client_info', 'shipper_id')
    op.drop_column('client_info', 'company_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_info', sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('client_info', sa.Column('shipper_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('client_info_shipper_id_fkey'), 'client_info', 'users', ['shipper_id'], ['id'])
    op.drop_column('client_info', 'company_vat_no')
    op.drop_column('client_info', 'tax_id')
    op.drop_column('client_info', 'company_registration_no')
    # ### end Alembic commands ###
