"""add columns in users table

Revision ID: ab32f02fff20
Revises: f310ddb7b8e8
Create Date: 2025-11-29 03:23:23.618544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab32f02fff20'
down_revision: Union[str, Sequence[str], None] = 'f310ddb7b8e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('contact_person', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'contact_person')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
