"""change model and schema

Revision ID: f310ddb7b8e8
Revises: a2a731255f22
Create Date: 2025-11-24 03:34:05.919310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f310ddb7b8e8'
down_revision: Union[str, Sequence[str], None] = 'a2a731255f22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_request_client_info', sa.Column('entry_date', sa.Date(), nullable=False))
    op.add_column('booking_request_client_info', sa.Column('method_type', sa.Enum('email', 'whats_app', 'verbal', 'in_person', 'other', name='methodenum', native_enum=False), nullable=False))
    op.drop_column('client_info', 'method_type')
    op.drop_column('client_info', 'entry_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_info', sa.Column('entry_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('client_info', sa.Column('method_type', sa.VARCHAR(length=9), autoincrement=False, nullable=False))
    op.drop_column('booking_request_client_info', 'method_type')
    op.drop_column('booking_request_client_info', 'entry_date')
    # ### end Alembic commands ###
