"""initial migration

Revision ID: f8f917784957
Revises: 
Create Date: 2025-11-10 05:18:08.802760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8f917784957'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_parties_id'), 'booking_parties', ['id'], unique=False)
    op.create_table('cargo_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cargo_types_id'), 'cargo_types', ['id'], unique=False)
    op.create_table('container_sizes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_container_sizes_id'), 'container_sizes', ['id'], unique=False)
    op.create_table('hs_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hs_codes_id'), 'hs_codes', ['id'], unique=False)
    op.create_table('ports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ports_id'), 'ports', ['id'], unique=False)
    op.create_table('request_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_types_id'), 'request_types', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user', 'manager', name='roleenum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('booking_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requested_date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type_of_request_id', sa.Integer(), nullable=False),
    sa.Column('booking_party_id', sa.Integer(), nullable=False),
    sa.Column('port_of_load_id', sa.Integer(), nullable=False),
    sa.Column('port_of_discharge_id', sa.Integer(), nullable=False),
    sa.Column('cargo_type_id', sa.Integer(), nullable=True),
    sa.Column('container_size_id', sa.Integer(), nullable=True),
    sa.Column('hs_code_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.String(length=50), nullable=True),
    sa.Column('weight_kg', sa.String(length=50), nullable=True),
    sa.Column('commodity', sa.String(length=255), nullable=True),
    sa.Column('shipping_lines', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['booking_party_id'], ['booking_parties.id'], ),
    sa.ForeignKeyConstraint(['cargo_type_id'], ['cargo_types.id'], ),
    sa.ForeignKeyConstraint(['container_size_id'], ['container_sizes.id'], ),
    sa.ForeignKeyConstraint(['hs_code_id'], ['hs_codes.id'], ),
    sa.ForeignKeyConstraint(['port_of_discharge_id'], ['ports.id'], ),
    sa.ForeignKeyConstraint(['port_of_load_id'], ['ports.id'], ),
    sa.ForeignKeyConstraint(['type_of_request_id'], ['request_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_requests_id'), 'booking_requests', ['id'], unique=False)
    op.create_table('booking_confirmations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carrier_name', sa.String(length=100), nullable=False),
    sa.Column('rates_confirmed', sa.String(length=255), nullable=True),
    sa.Column('booking_confirmation_no', sa.String(length=100), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=True),
    sa.Column('shipper', sa.String(length=255), nullable=True),
    sa.Column('port_of_load', sa.String(length=100), nullable=True),
    sa.Column('port_of_discharge', sa.String(length=100), nullable=True),
    sa.Column('vessel_name', sa.String(length=255), nullable=True),
    sa.Column('voyage', sa.String(length=100), nullable=True),
    sa.Column('container_size', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.String(length=50), nullable=True),
    sa.Column('weight_kg', sa.String(length=50), nullable=True),
    sa.Column('cy_cfs', sa.String(length=100), nullable=True),
    sa.Column('hs_code', sa.String(length=50), nullable=True),
    sa.Column('cargo_description', sa.String(length=255), nullable=True),
    sa.Column('booking_request_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['booking_request_id'], ['booking_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_confirmations_id'), 'booking_confirmations', ['id'], unique=False)
    op.create_table('client_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('billing_address', sa.String(length=500), nullable=True),
    sa.Column('shipping_address', sa.String(length=500), nullable=True),
    sa.Column('booking_request_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['booking_request_id'], ['booking_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_info_id'), 'client_info', ['id'], unique=False)
    op.create_table('invoice_previews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_to', sa.JSON(), nullable=False),
    sa.Column('invoice_info', sa.JSON(), nullable=False),
    sa.Column('shipping_details', sa.JSON(), nullable=True),
    sa.Column('container_details', sa.JSON(), nullable=True),
    sa.Column('itemized_charges', sa.JSON(), nullable=True),
    sa.Column('totals', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('booking_request_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['booking_request_id'], ['booking_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_previews_id'), 'invoice_previews', ['id'], unique=False)
    op.create_table('shipping_instructions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_of_bill_of_lading', sa.String(length=50), nullable=True),
    sa.Column('shipper', sa.JSON(), nullable=True),
    sa.Column('consignee', sa.JSON(), nullable=True),
    sa.Column('notify', sa.JSON(), nullable=True),
    sa.Column('vessel', sa.String(length=255), nullable=True),
    sa.Column('voyage', sa.String(length=100), nullable=True),
    sa.Column('booking_reference', sa.String(length=100), nullable=True),
    sa.Column('bill_of_lading_no', sa.String(length=100), nullable=True),
    sa.Column('port_of_load', sa.String(length=100), nullable=True),
    sa.Column('port_of_discharge', sa.String(length=100), nullable=True),
    sa.Column('etd_departure', sa.Date(), nullable=True),
    sa.Column('eta_arrival', sa.Date(), nullable=True),
    sa.Column('vehicles', sa.JSON(), nullable=True),
    sa.Column('marks_numbers', sa.JSON(), nullable=True),
    sa.Column('special_instructions', sa.String(length=1000), nullable=True),
    sa.Column('dangerous_goods', sa.Boolean(), nullable=True),
    sa.Column('temperature_control', sa.String(length=50), nullable=True),
    sa.Column('humidity_control', sa.String(length=50), nullable=True),
    sa.Column('booking_request_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['booking_request_id'], ['booking_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipping_instructions_id'), 'shipping_instructions', ['id'], unique=False)
    op.create_table('charges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_preview_id', sa.Integer(), nullable=True),
    sa.Column('charge_name', sa.String(length=255), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('taxable', sa.String(length=5), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('booking_request_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['booking_request_id'], ['booking_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_preview_id'], ['invoice_previews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charges_id'), 'charges', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_charges_id'), table_name='charges')
    op.drop_table('charges')
    op.drop_index(op.f('ix_shipping_instructions_id'), table_name='shipping_instructions')
    op.drop_table('shipping_instructions')
    op.drop_index(op.f('ix_invoice_previews_id'), table_name='invoice_previews')
    op.drop_table('invoice_previews')
    op.drop_index(op.f('ix_client_info_id'), table_name='client_info')
    op.drop_table('client_info')
    op.drop_index(op.f('ix_booking_confirmations_id'), table_name='booking_confirmations')
    op.drop_table('booking_confirmations')
    op.drop_index(op.f('ix_booking_requests_id'), table_name='booking_requests')
    op.drop_table('booking_requests')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_request_types_id'), table_name='request_types')
    op.drop_table('request_types')
    op.drop_index(op.f('ix_ports_id'), table_name='ports')
    op.drop_table('ports')
    op.drop_index(op.f('ix_hs_codes_id'), table_name='hs_codes')
    op.drop_table('hs_codes')
    op.drop_index(op.f('ix_container_sizes_id'), table_name='container_sizes')
    op.drop_table('container_sizes')
    op.drop_index(op.f('ix_cargo_types_id'), table_name='cargo_types')
    op.drop_table('cargo_types')
    op.drop_index(op.f('ix_booking_parties_id'), table_name='booking_parties')
    op.drop_table('booking_parties')
    # ### end Alembic commands ###
